id: dbeb13e3dd3e4ab585d2cbb3cf034a1c
initial_creation_type: ocr
source_metadata:
  volumes:
    3ff1283c6d374e5db976ca9edfdf4eab:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
