id: DB3034BD1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:45:21+00:00'
last_modified: '2022-05-27T15:52:13.361292+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b52c:
      image_group_id: I1PD95910
      title: འཕགས་པ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: b52c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
